FROM icr.io/appcafe/open-liberty:23.0.0.1-kernel-slim-java17-openj9-ubi

COPY --chown=1001:0  guide-maven-intro/finish/target/ServletSample.war /config/dropins/
COPY --chown=1001:0  guide-maven-intro/finish/target/liberty/wlp/usr/servers/guideServer/server.xml /config/

RUN /liberty/bin/featureUtility isf defaultServer

ARG VERBOSE=true

RUN configure.sh